name = "IPython"
uuid = "18364772-b071-5c00-bfd7-ceeaffab630a"

[deps]
Compat = "34da2185-b29b-5c13-b0c7-acf172513d20"
Conda = "8f4d0f93-b110-5947-807f-2305c1781a2d"
InteractiveUtils = "b77e0a4c-d291-57a0-90e8-8db25a27a240"
PyCall = "438e738f-606a-5dbb-bf0a-cddfbfd45ab0"
REPL = "3fa0cd96-eef1-5676-8a61-b3b8758bbffb"
